# -*- coding: utf-8 -*-
"""automatos celulares.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yYfudLHoLXYePCDVhzpPvWx-DkGod58O
"""

import random

def gerar_regra(numero):
    bits = f"{numero:08b}"
    padroes = [
        "111", "110", "101", "100",
        "011", "010", "001", "000"
    ]
    return dict(zip(padroes, bits))

def proxima_geracao(estado, regra, circular=True):
    n = len(estado)
    novo = []

    for i in range(n):
        if circular:
            esquerda = estado[(i-1)%n]
            direita = estado[(i+1)%n]
        else:
            esquerda = estado[i-1] if i > 0 else 0
            direita = estado[i+1] if i < n-1 else 0

        centro = estado[i]
        padrao = f"{esquerda}{centro}{direita}"
        novo.append(int(regra[padrao]))

    return novo

def mostrar(estado):
    print("".join("█" if x else " " for x in estado))



regra_num = int(input("Regra (0-255): "))
regra = gerar_regra(regra_num)

tam = 101

# 1. Definição Correta do Contorno (Bordas)
tipo_borda = input("Contorno/Borda (c=circular/periódico, f=fixo com zero): ").strip().lower()
circular = (tipo_borda == "c")

# 2. Definição do Estado Inicial
op = input("Inicial (u=único, a=aleatório): ").strip().lower()

if op == "u":
    # Sítio Único: cria tudo zerado com apenas 1 elemento no centro
    estado = [0] * tam
    estado[tam // 2] = 1
else:
    densidade = float(input("Densidade de células ocupadas (0.0 a 1.0): "))
    distribuicao = input("Distribuição espacial (g=agrupado, e=espalhado): ").strip().lower()

    if distribuicao == "e":
        # Espalhado: decide célula por célula usando a probabilidade da densidade
        estado = [1 if random.random() < densidade else 0 for _ in range(tam)]
    else:
        # Agrupado: calcula a quantidade total de células pretas e junta todas no meio
        estado = [0] * tam
        num_ocupados = int(tam * densidade)
        inicio = (tam - num_ocupados) // 2
        for i in range(inicio, inicio + num_ocupados):
            estado[i] = 1

# --- EXECUÇÃO DO LAÇO ---
print("\nResultado da Evolução:\n")
for _ in range(50):
    mostrar(estado)
    estado = proxima_geracao(estado, regra, circular)

"""---"""